name: flutter_keycloak_example
description: Demonstrates how to use FlutterKeycloak

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_keycloak:
    path: ../
  get_storage: ^2.1.1

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
