name: flutter_keycloak
description: A Flutter Keycloak wrapper, to manage the authentication and tokens automatically
version: 1.1.5
homepage: https://github.com/TheFe91/flutter_keycloak

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  get_storage: ^2.0.3

dev_dependencies:
  flutter_lints: ^3.0.1

flutter: